{% set name = "audio_tools" %}
{% set version = environ.get("RELEASE_VERSION") or "0.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: {{ environ.get("SRC_PATH") }}

build:
  number: 1
  script_env:
    - CMAKE_BUILD_TYPE=Release
    - CMAKE_CONFIG_TYPE=Release

requirements:
  build:
    - ros-jazzy-desktop
    - sdl2 >=2.26,<3.0

    {% if target_platform != "win-64" %}
    - libgcc-ng
    - libstdcxx-ng
    {% endif %}

    # Optional: only include on macOS
    {% if target_platform == "osx-64" or target_platform == "osx-arm64" %}
    - libcxx
    {% endif %}

    - libffi

  run:
    - ros-jazzy-desktop
    - sdl2 >=2.26,<3.0

    {% if target_platform != "win-64" %}
    - libgcc-ng
    - libstdcxx-ng
    {% endif %}

    {% if target_platform == "osx-64" or target_platform == "osx-arm64" %}
    - libcxx
    {% endif %}

    - libffi
    - openssl


about:
  summary: "ROS 2 audio capture/processing tools"
  license: "Apache-2.0"
  home: "https://github.com/CLFML/ROS2_Audio_Tools"
