# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
package:
  name: ros2-audio-tools
  version: VER{0.0.0}

source:
  - path: 'C:\src'

build:
  number: 4
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

outputs:
  - package:
      name: ros-jazzy-audio-tools
      version: VER{0.0.0}
    about:
      homepage: https://www.ros.org/
      license: BSD-3-Clause
      summary: "Audio tools for ROS2 containing:\n  - Audio capture node; Which able to capture audio from your microphone"
      maintainers: []
    extra:
      recipe-maintainers:
        - robostack
    build:
      number: 0
      script: 'bld_ament_cmake.bat'
    requirements:
      build:
        - msbuild
        - ninja
        - python
        - make
        - setuptools
        - m2-patch
        - cmake
        - python
        - numpy
      host:
        - ros-jazzy-ament-cmake
        - ros-jazzy-rosidl-default-generators
        - ros-jazzy-rclcpp
        - ros-jazzy-std-msgs
        - ros-jazzy-sdl2-vendor
        - ros-jazzy-rclcpp
        - ros-jazzy-std-msgs
        - ros-jazzy-sdl2-vendor
        - ros-jazzy-ament-lint-auto
        - ros-jazzy-ament-lint-common
      run:
        - ros-jazzy-rclcpp
        - ros-jazzy-std-msgs
        - ros-jazzy-sdl2-vendor
        - ros-jazzy-rosidl-default-runtime
        - ros-jazzy-rclcpp
        - ros-jazzy-std-msgs
        - ros-jazzy-sdl2-vendor

