name: Create ROS2 Jazzy package on Windows

on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.3

      - name: Build conda package with Pixi
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          :: Get release version from GitHub, strip leading 'v'
          FOR /F "delims=" %%A IN ('gh release view --json tagName --jq ".tagName"') DO (
            SET "RELEASE_VERSION=%%A"
          )
          SET "RELEASE_VERSION=%RELEASE_VERSION:v=%"

          :: Create isolated build workspace
          mkdir "C:\build\src"

          :: Copy files except .pixi, pixi.toml, .git
          robocopy . "C:\build\src" /E /XD .pixi .git /XF pixi.toml

          :: Copy conda recipe
          robocopy conda "C:\build\conda" /E

          :: Set SRC_PATH
          SET "SRC_PATH=C:\build\src"

          :: Add build dependencies
          pixi add conda-build conda-verify

          :: Run the build
          pixi run conda build . -c https://prefix.dev/robostack-jazzy -c conda-forge --croot C:\build

      - name: Upload Windows Conda Package to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          # Get the release tag name
          TAG_NAME=$(gh release view --repo CLFML/ROS2_Audio_Tools --json tagName --jq ".tagName")

          # Locate the .conda file
          PACKAGE_PATH=$(ls C:/build/win-64/*.conda | head -n 1)

          # Copy and rename with `-win` suffix in filename
          WIN_PACKAGE_PATH="${PACKAGE_PATH%.conda}-win.conda"
          cp "$PACKAGE_PATH" "$WIN_PACKAGE_PATH"

          # Upload the renamed file
          gh release upload "$TAG_NAME" "$WIN_PACKAGE_PATH" --repo CLFML/ROS2_Audio_Tools --clobber
