name: Create ROS2 Jazzy package on Windows

on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: C:\cw
      - name: Move src to root (everything except .pixi, .git, pixi.toml, conda)
        shell: cmd
        working-directory: C:\cw
        run: |
          robocopy C:\cw\src C:\src /E /XD .pixi .git conda /XF pixi.toml
      - name: Change release version to environment variable
        shell: pwsh
        working-directory: C:\cw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $release = (gh release view --json tagName --jq ".tagName")
          $version = $release -replace "^v", ""
          $env:RELEASE_VERSION = $version

          robocopy "conda/win" "." /E
          Remove-Item -Recurse -Force "conda"

         (Get-Content "recipe/recipe.yaml") -replace 'VER{0.0.0}', $env:RELEASE_VERSION | Set-Content "recipe/recipe.yaml"
      - name: Install Pixi
        working-directory: C:\cw
        uses: prefix-dev/setup-pixi@v0.8.3

      - name: Build conda package with Pixi
        working-directory: C:\cw
        shell: cmd
        run: |
          pixi run boa build .

      - name: Upload Windows Conda Package to GitHub Release
        working-directory: C:\cw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
         $tag = gh release view --repo CLFML/ROS2_Audio_Tools --json tagName --jq ".tagName"
         $pkg = Get-ChildItem "C:/cw/.pixi/envs/default/conda-bld/win-64/*.tar.bz2" | Select-Object -First 1
         $renamed = $pkg.FullName -replace '\.conda$', '-win.conda'
         Copy-Item $pkg.FullName $renamed
         gh release upload $tag $renamed --repo CLFML/ROS2_Audio_Tools --clobber
