name: Create ROS2 Jazzy package on Linux

on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Prepare home/src directory
        run: |
          mkdir ~/src
          rsync -av --exclude='.git' --exclude='.github' --exclude='conda' ./ /home/runner/src/

      - name: Copy recipe to home/recipe
        run: |
          mkdir ~/recipe
          cp -r conda/lin/* ~/recipe

      - name: Inject release version into recipe.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export RELEASE_VERSION="$(gh release view --json tagName --jq .tagName | sed 's/^v//')"
          
          cd ~/recipe
          sed -i "s/VER{0.0.0}/\"$RELEASE_VERSION\"/g" recipe/recipe.yaml

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
         run-install: false
      
      - name: Install Pixi environment
        working-directory: /home/runner/recipe
        run: |
           pixi install
 
      - name: Build package with Pixi
        working-directory: /home/runner/recipe
        shell: pixi run bash -e {0}
        run: |
          conda config --add channels https://prefix.dev/robostack-jazzy
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          chmod +x recipe/*.sh
          boa build .
           
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $(gh release view --repo CLFML/ROS2_Audio_Tools --json tagName --jq ".tagName")  /home/runner/recipe/.pixi/envs/default/conda-bld/linux-64/ros-jazzy-*.tar.bz2
