name: Create ROS2 Jazzy package on Linux

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
      

      - name: Install Pixi environment
        run: |
          pixi install

      - name: Run colcon build (Release Mode)
        run: |
          cd robostack
          pixi run build
